name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 8 * * 5'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: temurin
    - uses: coursier/cache-action@v6
    - run: git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
    - run: git show --oneline --check
    - run: sbt -v
           "+ scalafmtCheckAll"
           scalafmtSbtCheck
           "+ Test/compile"
           "+ msgpack4z-circeJVM/test"
           "+ msgpack4z-circeJS/test"
